-- CoreData tables
CREATE TABLE Z_METADATA (
    Z_VERSION INTEGER PRIMARY KEY,
    Z_UUID VARCHAR(255),
    Z_PLIST BLOB
);

CREATE TABLE Z_PRIMARYKEY (
    Z_ENT INTEGER PRIMARY KEY,
    Z_NAME VARCHAR,
    Z_SUPER INTEGER,
    Z_MAX INTEGER
);

-- App data tables
CREATE TABLE ZVALUABLEKEY (
    Z_PK INTEGER PRIMARY KEY,
    Z_ENT INTEGER,
    Z_OPT INTEGER,
    ZCOMPRESSEDTOTALBALANCE FLOAT,
    ZCOMPRESSEDTOTALRECIVED FLOAT,
    ZCOMPRESSEDUNCONFIRMEDBALANCE FLOAT,
    ZUNCOMPRESSEDTOTALBALANCE FLOAT,
    ZUNCOMPRESSEDTOTALRECIVED FLOAT,
    ZUNCOMPRESSEDUNCONFIRMEDBALANCE FLOAT,
    ZCOMPRESSEDKEY VARCHAR,
    ZPRIVATEKEY VARCHAR,
    ZUNCOMPRESSEDKEY VARCHAR,
    ZWIF VARCHAR
);

CREATE UNIQUE INDEX Z_ValuableKey_UNIQUE_privateKey
ON ZVALUABLEKEY (ZPRIVATEKEY COLLATE BINARY ASC);

CREATE TABLE ZSEARCHENTITY (
    Z_PK INTEGER PRIMARY KEY,
    Z_ENT INTEGER,
    Z_OPT INTEGER,
    ZDATE TIMESTAMP,
    ZENDKEY VARCHAR,
    ZSTARTKEY VARCHAR
);

CREATE UNIQUE INDEX Z_SearchEntity_UNIQUE_startKey
ON ZSEARCHENTITY (ZSTARTKEY COLLATE BINARY ASC);

CREATE TABLE Z_MODELCACHE (
    Z_CONTENT BLOB
);
